jdbc.driverClassName=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://localhost:3306/uniwersal
jdbc.username=root
jdbc.password=dupa98
database.encoding=latin1
supplier.nr=3
skup.url=http://18492-1-85557b-01.services.oktawave.com:8080/skup
skup.username=marcin
skup.password=gibson1
pdfView.(class)=com.technicalkeeda.view.PDFView