INSERT INTO config VALUES (1,'Ilosc kolumn przy wazeniu','10',1);
INSERT INTO config VALUES (2,'Wielkosc fontow przy wazeniu','6',1);
INSERT INTO config VALUES (3,'Ilosc kolumn przy wyborze rodzaju','5',1);
INSERT INTO config VALUES (4,'Wielkosc fontow przy wyborze rodzaju','6',1);
INSERT INTO config VALUES (5,'Ilosc kolumn przy wyborze grupy/hali','3',1);
INSERT INTO config VALUES (6,'Wielkosc fontow przy wyborze grupy/hali','6',1);
INSERT INTO config VALUES (7,'Sprzedaz zmniejsza stan skrzynek','0',1);
INSERT INTO config VALUES (8,'Aktywny magazyn skrzynek','0',1);
INSERT INTO config VALUES (9,'Aktywne rozliczenia zbieraczek','3',1);
INSERT INTO config VALUES (10,'Aktywna historia wozkow','1',1);
INSERT INTO config VALUES (11,'Historia sprzedazy','0',1);
INSERT INTO config VALUES (12,'Nabijanie wielu skrzynek jednoczesnie','1',1);
INSERT INTO config VALUES (13,'Pokazuj wykresy','0',1);
INSERT INTO config VALUES (14,'Raporty wg Dat','1',1);
INSERT INTO config VALUES (15,'Logowanie do programu','1',0);
INSERT INTO config VALUES (16,'Wprowadzanie skrzyneczek poprzez numery zbieraczek','0',1);
INSERT INTO config VALUES (17,'Resetowanie mnoznika skrzynek przy nawazaniu','1',1);
INSERT INTO config VALUES (18,'Przeliczaj minuty zbierania na godziny:minuty','1',1);
INSERT INTO config VALUES (19,'Obsluga skanera','1',1);
INSERT INTO config VALUES (20,'Zatwierdzanie palet przez magazyniera','0',1);
INSERT INTO config VALUES (21,'Aktywne zamowienia','1',1);
