'use strict';

angular.module('myTranslator', ['pascalprecht.translate'])
  .config(['$translateProvider', function ($translateProvider) {
    $translateProvider.translations('pl', {
      'error': 'Coś poszło nie tak :(',
      'error.concurrentWrite': 'Dane zostały zmienione przez innego użytkownika',
      'error.digitOnly': 'Proszę wprowadzać jedynie cyfry',
      'kg': 'kg',
      'pcs': 'szt.',
      'submit': 'Zapisz',
      'cancel': 'Anuluj',
      'loading': 'Ładowanie',
      'TITLE': 'Uniwersal',
      'HEADER.REPORTS_MENU': 'Statystyki',
      'HEADER.LEADER_REPORT': 'Zbieraczki',
      'HEADER.WORKTIME_REPORT': 'Czas pracy',
      'HEADER.SCALE_STATUS': 'Stany wag',
      'HEADER.CHAMBER_STATUS': 'Zbiory wg hal',
      'HEADER.CYCLES_BY_BRIGADES': 'Brygady w halach',
      'HEADER.SIZE_BY_CYCLE': 'Rozmiar grzybów',
      'HEADER.SCALE_MAN_MENU': 'Wózkowy',
      'HEADER.CYCLES': 'Hale',
      'HEADER.PEOPLE': 'Pracownicy',
      'HEADER.ADMIN': 'Administracja',
      'HEADER.SETTINGS': 'Ustawienia',
      'HEADER.PAYROLL': 'Płace',
      'HEADER.WAREHOUSE': 'Magazyn',
      'HEADER.ORDERS': 'Zamówienia',
      'HEADER.EASTWAREHOUSE': 'Skup',
      'HEADER.reclassificationTypes': 'Rodzaje grzybów',
      'HEADER.productionOrders':'Zamówienia',
      'HEADER.reclassificationHeaders': 'Oczekujące przeklasyfikowania',
      'HEADER.reclassificationHistory': 'Zaimportowane przeklasyfikowania',
      'HEADER.SCANNER_MAN_REPORT': 'Praca Wózkowych',
      'HEADER.TROLLEY_MAN_REPORT': 'Praca Wagowych',
      'HEADER.palette-type':'Palety',
      'HEADER.SALES_REPORT': 'Raport sprzedaży',
      'header.reports.types-by-pickers': 'Zbiory wg zbieraczek',
      'header.logout': 'Wyloguj',
      'LEADER_REPORT.HEADER': 'Zbieraczki',
      'leader_report.id': 'Id',
      'leader_report.nr': 'Nr',
      'leader_report.name': 'Imię',
      'leader_report.surname': 'Nazwisko',
      'leader_report.groupName': 'Grupa',
      'leader_report.export': 'Eksport',
      'leader_report.kraj': 'Kraj',
      'leader_report.sum': 'Suma',
      'leader_report.inne': 'Inne',
      'leader_report.summary': 'Łączna waga',
      'leader_report.exportFactor': 'Procent Exportu',
      'leader_report.hours': 'Ilość Godzin',
      'leader_report.totalPerHour': 'Kg/godz',
      'leader_report.tested': 'Sprawdzone',
      'leader_report.rejected': 'Odrzucone',
      'leader_report.total': 'Suma: ',
      'leader_report.end-date.before.start-date': 'Data końca przed datą początku',
      'scannerManReport.header': 'Praca Wózkowych. Raport podaje wyniki sztukach wprowadzonych skrzyneczek!',
      'scannerManReport.person': 'Wózkowy',
      'scannerManReport.total': 'Suma sztuk',
      'scannerManReport.total.kg': 'Suma kg',
      'scannerManReport.inne': 'Inne',
      'scannerManReport.kraj': 'Kraj',
      'scannerManReport.export': 'Eksport',
      'scannerManReport.quality': 'Jakość',
      'scannerManReport.pcs': 'szt.',
      'scale_status.header': 'Stany wag',
      'scale_status.scaleMan': 'Wagowy',
      'scale_status.type': 'Rodzaj',
      'scale_status.amount': 'Ilość sztuk',
      'scale_status.weight': 'Łączna waga',
      'scale_status.total': 'Suma',
      'collected_by_chamber.title': 'Zbiory wg hal',
      'collected_by_chamber.name': 'Hala',
      'collected_by_chamber.kraj': 'Suma kraju',
      'collected_by_chamber.export': 'Suma eksport',
      'collected_by_chamber.inne': 'Suma innych',
      'collected_by_chamber.exportRatio': '% eksportu',
      'collected_by_chamber.total': 'Suma',
      'size-by-cycle.breadcrumb.title': 'Zbiory w cyklach wg rozmiaru grzybów',
      'size-by-cycle.total': 'Suma',
      'size-by-cycle.cycle-name': 'Wielkość',
      'scanner.header': 'Skaner',
      'scanner.breadcrumb.scanner': 'skaner',
      'scanner.breadcrumb.total': 'podsumowanie',
      'scanner.breadcrumb.detail': 'edycja wózka',
      'scanner.breadcrumb.summary': 'zestawienie',
      'scanner.total.trolleyId': 'Numer wózka',
      'scanner.total.type': 'Rodzaj',
      'scanner.total.weight': 'Waga jednostkowa',
      'scanner.total.total':'Suma',
      'scanner.total.totalPcs': 'Ilość sztuk',
      'scanner.total.totalWeight': 'Łączna waga',
      'scanner.total.commit.success.message': 'Pomyślnie zatwierdzono paletę ',
      'scanner.total.commit.error.message': 'Błąd zatwierdzania palety!',
      'scanner.total.commit.header': 'Niezatwierdzone palety',
      'scanner.total.commit.wait': 'Poczekalnia',
      'scanner.total.commit.edit': 'Edycja',
      'scanner.total.commit.submit': 'Zatwierdzenie do chmury',
      'scanner.total.commit-to-warehouse.submit': 'Zatwierdzenie na magazyn',
      'scanner.total.commit.restore': 'Przywróc',
      'scanner.total.commit.summary': 'Zestawienie',
      'scanner.total.summary.picker': 'Zbieraczka',
      'scanner.total.summary.type': 'Rodzaj',
      'scanner.total.summary.chamber': 'Hala',
      'scanner.total.summary.totalAmount': 'Ilość sztuk',
      'scanner.total.summary.totalWeight': 'Łączna waga',
      'scanner.total.summary.summary': 'Suma',
      'scanner.detail.barcode': 'Kod kreskowy',
      'scanner.detail.remove.trolley.button': 'Usuń paletę',
      'scanner.detail.type': 'Rodzaj',
      'scanner.detail.weight': 'Waga jednostkowa',
      'scanner.detail.chamber': 'Hala',
      'scanner.detail.picker.id': 'Id zbieraczki',
      'scanner.detail.picker.name': 'Imię',
      'scanner.detail.picker.surname': 'Nazwisko',
      'scanner.detail.leader.name': 'Brygadzistka:  Imię',
      'scanner.detail.leader.surname': 'Nazwisko',
      'scanner.detail.trolleyMan.name': 'Wózkowy:  Imię',
      'scanner.detail.trolleyMan.surname': 'Nazwisko',
      'scanner.message.boxAdded': 'Wprowadzona skrzyneczka dla ',
      'scanner.message.notADigit': 'To nie jest cyfra',
      'scanner.message.invalidSupplierCode': 'Niewłaściwy numer pieczarkarni',
      'scanner.message.invalidPickerId': 'Niewłaściwy numer zbieraczki',
      'scanner.message.chooseChamber': 'Proszę wybrać halę',
      'scanner.message.chooseType': 'Proszę wybrać rodzaj',
      'scanner.message.chooseLeader': 'Proszę wybrać brygadzistkę',
      'scanner.message.chooseTrolleyMan': 'Proszę wybrać wózkowego',
      'scanner.messsage.noReservedBarcode': 'Kod nie został zarezerwowany',
      'scanner.message.barcodeUsed': 'Kod został już użyty',
      'scanner.qualityCheck': 'Wynik kontroli jakości: ',
      'scanner.qualityCheck.notChecked': 'Niesprawdzone',
      'scanner.qualityCheck.ok': 'Pozytywny',
      'scanner.qualityCheck.notOk': 'Negatywny',
      'scanner.type': 'Rodzaj',
      'scanner.chamber': 'Hala',
      'scanner.leader': 'Brygadzistka',
      'scanner.trolleyMan': 'Wagowy',
      'scanner.button.summary': 'Podsumowanie',
      'scanner.orders.header':'Zamówienia na',
      'scanner.typeName':'Rodzaj',
      'scanner.collectedAmount':'Ilość zebranych sztuk',
      'scanner.dueAmount':'Ilość zamówionych sztuk',
      'scanner.commit.harvest.palette.to.warehouse.header.1': 'Zatwierdzanie palet',
      'scanner.commit.harvest.palette.to.warehouse.header.2': 'wprost do chłodni',
      'scanner.commit.harvest.palette.to.warehouse.type': 'Rodzaj',
      'scanner.commit.harvest.palette.to.warehouse.totalAmount': 'Łączna ilość',
      'scanner.commit.harvest.palette.to.warehouse.totalWeight': 'Łączna waga',
      'scanner.commit.harvest.palette.to.warehouse.trolleyNo': 'Numer palety',
      'scanner.commit.harvest.palette.to.warehouse.totals':'Suma',
      'scanner.commit.harvest.palette.to_warehosue.paletteType':'Typ palety',
      'manualBoard.header': 'Masowe wprowadzanie',
      'cycle.headers': 'Cykle',
      'cycleHeaders.hala_name': 'Hala',
      'cycleHeaders.startDay': 'Data założenia',
      'cycleHeaders.endDay': 'Data zakończenia',
      'cycleHeaders.export': 'Export',
      'cycleHeaders.kraj': 'Kraj',
      'cycleHeaders.total': 'Suma',
      'cycleHeaders.quality': 'Jakość',
      'cycleHeaders.byTone': 'Wydajność z Tony',
      'cycleHeaders.byMeter': 'Wydajność z Metra',
      'cycleHeaders.kompostownia': 'Kompostownia',
      'cycleHeaders.grzybnia': 'Grzybnia',
      'cycleDetails.startDate': 'Początek',
      'cycleDetails.koniec1': 'Początek II rzutu',
      'cycleDetails.koniec2': 'Początek III rzutu',
      'cycleDetails.koniec': 'Koniec (przeniesienie do archiwum)',
      'cycleDetails.kompostownia': 'Kompostownia',
      'cycleDetails.grzybnia': 'Grzybnia',
      'cycleDetails.torf': 'Torf',
      'cycleDetails.dok_okr': 'Dokarmiacz Okrywy',
      'cycleDetails.dok_pod': 'Dokarmiacz Podłoża',
      'cycleDetails.stopien_ubicia': 'Stopień Ubicia',
      'cycleDetails.kaking': 'Kaking',
      'cycleDetails.wilgotnosc': 'Wilgotność %',
      'cycleDetails.kg_podloza': 'Masa Podłoża w kg',
      'cycleDetails.metry': 'Powierzchnia Uprawy',
      'people.breadcrumb.people': 'pracownicy',
      'people.breadcrumb.add': 'dodaj pracownika',
      'people.breadcrumb.barcodes': 'kody kreskowe',
      'people.breadcrumb.edit': 'edycja danych',
      'people.breadcrumb.badge': 'rejestracja identyfikatora',
      'people.breadcrumb.timeSheet': 'Czas obecności w pracy',
      'people.breadcrumb.editTimeSheet': 'edycja czasu obecności w pracy',
      'people.people': 'Pracownicy',
      'peopleHeaders.id': 'Id',
      'peopleHeaders.nr': 'Nr',
      'peopleHeaders.name': 'Imię',
      'peopleHeaders.surname': 'Nazwisko',
      'peopleHeaders.group': 'Grupa',
      'peopleHeaders.edit': 'Edycja',
      'peopleHeaders.search': 'Szukaj',
      'peopleHeaders.add': ' Dodaj pracownika',


      'people.origin.switch': 'Narodowość',
      'people.origin.switch.on': 'Obcokrajowcy  ',
      'people.origin.switch.off': 'Wszyscy    ',
      'people.alert.breadcrumb.people': 'Pracownicy',
      'people.alert.breadcrumb.config': 'Ustawienia alertów',
      'people.alert.breadcrumb.config.subtitle': 'Ilość dni do uruchomienia alertu o wygaśnięciu terminu. Zero dni wyłącza alert.',
      'people.alert.visaDays': 'Termin ważności wizy',
      'people.alert.statementDays': 'Termin wygaśnięcia pozwolenia/oświadczenia',
      'people.alert.passportDays': 'Termin ważności paszportu',
      'people.alert.stayDays': 'Termin końca zameldowania',
      'people.alert.save': 'Zapisz',
      'people.alert.message.success': 'Terminy alertów pomyślnie zmienione',
      'peopleActiveSwitch.on': 'Wszyscy',
      'peopleActiveSwitch.off': 'Pracujący',
      'peopleEditTooltip': 'Edycja danych pracownika',
      'peopleHistoryTooltip': 'Historia zatrudnienia',
      'people.badgeRegistration.header': 'Rejestracja identyfikatora dla ',
      'people.badgeRegistration.message': 'Proszę zbliżyć identyfikator do czytnika.',
      'people.badgeRegistration.message.success': 'Identyfikator zarejestrowany pomyślnie.',
      'people.badgeRegistration.message.error.duplication': 'Identyfikator jest już przypisany do innej osoby.',
      'people.badgeRegistration.message.notChanged': 'Identyfikator bez zmian',
      'people.badgeRegistration.message.badgeRemoved': 'Identyfikator został pomyślnie usunięty.',
      'people.badgeRegistration.message.error.concurrentWrite': 'Dane zmienione przez innego użytkownika',
      'people.badgeRegistration.remove': ' usuń identyfikator',
      'people.timesheet.date': 'Data',
      'people.timesheet.all': 'Łącznie',
      'people.timesheet.work': 'Praca',
      'people.timesheet.pause': 'Przerwy',
      'people.timesheet.edit.save': 'Zapisz',
      'people.timesheet.edit.delete': 'Usuń',
      'people.timesheet.edit.add': 'Dodaj',
      'people.timesheet.edit.close': 'Zamknij',
      'people.timesheet.edit.message.invalid.period': 'Wybrany okres koliduje z istniejącym czasem pracy',
      'people.timesheet.edit.message.period-created': 'Nowa obecność utworzona',
      'people.timesheet.edit.message.period-deleted': 'Obecność usunięta',
      'people.timesheet.edit.message.period-updated': 'Godziny pracy zmienione',
      'people.timesheet.edit.message.period-closed': 'Okres pracy zamknięty',
      'people.timesheet.edit.message.start-after-begining': 'Godzina rozpoczęcia pracy nie może być późniejsza niż godzina jej zakończenia',
      'people.barcodes.header.id': 'Id',
      'people.barcodes.header.nr':'Nr',
      'people.barcodes.header.picker': 'Osoba',
      'people.barcodes.header.example': 'Budowa kodu',
      'people.barcodes.header.amount': 'Ilość zarezerwowanych',
      'people.barcodes.header.highest': 'Najwyższy numer',
      'people.barcodes': 'Kody kreskowe',
      'people.barcodes.button.remove': 'Usuń',
      'people.barcodes.button.reserve': 'Rezerwuj',
      'people.barcodes.button.show': 'Pokaż zarezerwowane',
      'people.barcodes.message.barcodes.created': 'Kody pomyślnie utworzone',
      'people.barcodes.message.barcodes.removed': 'Kody pomyślnie usunięte',
      'people.barcodes.delete.modal.header': 'Usuń rezerwację kodów',
      'people.barcodes.delete.modal.button.save': 'Usuń',
      'people.barcodes.delete.modal.button.cancel': 'Anuluj',
      'people.barcodes.list.modal.header': 'Lista zarezerwowanych kodów',
      'people.barcodes.list.modal.button.close': 'Zamknij',
      'people.barcodes.header.error.to-long-person-nr': 'Opcja wspierająca kody East Mushrooms może być używana jedynie do numeru zbieraczki 99',
      'people.worktime': 'Czas pracy',
      'people.worktime.breadcrumb': 'Czas pracy',

      'pickerEdit.id': 'Id',
      'pickerEdit.nr': 'Nr',
      'pickerEdit.name': 'Imię',
      'pickerEdit.surname': 'Nazwisko',
      'pickerEdit.mobile': 'Nr telefonu',
      'pickerEdit.address': 'Adres',
      'pickerEdit.active': 'Zwolnij',
      'pickerEdit.inactive': 'Przywróć',
      'pickerEdit.birthDate': 'Data urodzenia',
      'pickerEdit.poczatekWaznosciZezwolenia': 'Początek ważnosci zezwolenia',
      'pickerEdit.koniecWaznosciZezwolenia': 'Koniec ważnosci zezwolenia',
      'pickerEdit.dataZameldowania': 'Data zameldowania',
      'pickerEdit.dataWymeldowania': 'Data wymeldowania',
      'pickerEdit.yearBars': 'Historia zatrudnienia',
      'pickerEdit.startdDate': 'Początek zatrudnienia',
      'pickerEdit.endDate': 'Koniec zatrudnienia',
      'pickerEdit.group': 'Grupa',
      'pickerEdit.city': 'Miasto',
      'pickerEdit.indeks': 'Indeks',
      'pickerEdit.rejon': 'Rejon',
      'pickerEdit.imionaRodzicow': 'Imiona rodzicow',
      'pickerEdit.pesel': 'pesel',
      'pickerEdit.nrWizy': 'Numer wizy',
      'pickerEdit.passportNo': 'Numer paszportu',
      'pickerEdit.statementNo': 'Numer oświadczenia',
      'pickerEdit.permitNo': 'Numer pozwolenia',
      'pickerEdit.save': 'Zapisz',
      'pickerEdit.close': 'Zamknij',
      'pickerEdit.payrollStatus': 'Sposób wynagradzania',
      'pickerEdit.status.zero': 'Stawka godzinowa',
      'pickerEdit.status.one': 'Akord',
      'pickerEdit.status.two': 'Akord z dodatkami',
      'pickerEdit.regularWage': 'Stawka godzinowa za dni powszednie',
      'pickerEdit.sundayWage': 'Stawka godzinowa za dni niedziele',
      'pickerEdit.bonusWage': 'Stawka godzinowa za dni święta',
      'pickerEdit.isForeigner': 'Obcokrajowiec',
      'pickerEdit.message.picker-data-updated': 'Dane pracownika zapisane',
      'personAdd.name': 'Imię',
      'personAdd.surname': 'Nazwisko',
      'personAdd.nr': 'Numer',
      'personAdd.mobile': 'Nr telefonu',
      'personAdd.address': 'Adres',
      'personAdd.active': 'Zwolnij',
      'personAdd.inactive': 'Przywróć',
      'personAdd.birthDate': 'Data urodzenia',
      'personAdd.dataWaznosciZezwolenia': 'Data ważnosci zezwolenia',
      'personAdd.dataZameldowania': 'Data rozpoczęcia pracy',
      'personAdd.dataWymeldowania': 'Data zakończenia pracy',
      'personAdd.group': 'Grupa',
      'personAdd.city': 'Miasto',
      'personAdd.indeks': 'Indeks',
      'personAdd.rejon': 'Rejon',
      'personAdd.imionaRodzicow': 'Imiona rodzicow',
      'personAdd.pesel': 'pesel',
      'personAdd.nrWizy': 'Numer wizy',
      'personAdd.koniecWaznosciWizy': 'Koniec ważności wizy',
      'personAdd.nrPaszportu': 'Numer paszportu',
      'personAdd.nrOswiadczenia': 'Numer oświadczenia',
      'personAdd.nrZezwolenia': 'Numer pozwolenia',
      'personAdd.koniecWaznosciPaszportu': 'Termin ważności paszportu',
      'personAdd.poczatekWaznosciZezwolenia': 'Początek zezwolenia/oświadcznia',
      'personAdd.koniecWaznosciZezwolenia': 'Koniec zezwolenia/oświadcznia',
      'personAdd.poczatekZameldowania': 'Początek zameldowania',
      'personAdd.koniecZameldowania': 'Koniec zameldowania',
      'personAdd.save': 'Zapisz',
      'personAdd.success.message': 'Dodano pracownika',
      'personAdd.success.message.id': 'Id',
      'personAdd.success.message.nr': 'nr',
      'personAdd.success.message.name': 'Imie',
      'personAdd.success.message.surname': 'Nazwisko',
      'personAdd.isForeigner': 'Obcokrajowiec',
      'personAdd.days_number': 'Ilość dni',
      'person.barcode.submit': 'Utwórz',
      'person.barcode.remove': 'Usuń rezerwację',
      'person.barcode.showAll': 'Pokaż wszystkie',
      'person.barcode.hideAll': 'Ukryj',
      'person.barcode.created.message': 'Dodano nowe kody:',
      'person.barcode.deleted.message': 'Kody usunięte.',
      'person.barcode.freeCodes.amount': 'Ilość wolnych kodów: ',
      'person.barcode.picker.code': 'Kod zbieraczki:',
      'person.barcode.leader.code': 'Kod brygadzistki:',
      'person.barcode.trolleyMan.code': 'Kod wózkowego:',
      'person.barcode.removeBarcodes.title': 'Zaznacz zakres kodów do usunięcia',
      'person.barcode.removeBarcodes.cancel': 'Anuluj',
      'person.barcode.removeBarcodes.submit': 'Usuń',
      'person.changePassword.password': 'Nowe hasło:',
      'person.alt.change-password': 'Zmień hasło',
      'person.alt.reserve-barcode': 'Rezerwacja kodów kreskowych',
      'person.alt.badge-register': 'Rejestracja identyfikatora RFID',
      'person.alt.edit-person': 'Edycja danych pracownika',
      'person.alt.clock': 'Edycja czasu pracy',
      'personYearStatus.title': 'Historia zatrudnienia',
      'reclassification.rodzaj.header': 'Przypisanie rodzajów ze skupu do lokalnych rodzajów.',
      'reclassification.rodzaj.nr': '#',
      'reclassification.rodzaj.name': 'Rodzaj',
      'reclassification.rodzaj.weight': 'Waga',
      'reclassification.rodzaj.assigned': 'Rodzaj na skupie',
      'reclassification.header.id': 'Nr',
      'reclassification.header.remoteId': 'Numer na skupie',
      'reclassification.header.description': 'Opis',
      'reclassification.header.date': 'Data',
      'reclassification.header.amount': 'Ilość skrzyneczek',
      'reclassification.details.header.1': 'Przeklasyfikowanie nr ',
      'reclassification.details.header.2': 'z dn. ',
      'reclassification.details.barcode': 'Kod kreskowy',
      'reclassification.details.hala': 'Hala',
      'reclassification.details.date': 'Data zbioru',
      'reclassification.details.beforeTypeName': 'Rodzaj przed przeklasyfikowaniem',
      'reclassification.details.afterTypeName': 'Rodzaj po przeklasyfikowaniu',
      'reclassification.details.remoteTypeName': 'Rodzaj ze skupu',
      'reclassification.details.pickerId': 'Id zbieraczki',
      'reclassification.details.pickerNr': 'Nr zbieraczki',
      'reclassification.details.pickerName': 'Imię i Nazwisko zbieraczki',
      'reclassification.details.pickerGroupName': 'Grupa',
      'reclassification.details.wagowy': 'Wagowy',
      'reclassification.details.massage': 'Uwagi',
      'reclassification.details.active': 'Włącz',
      'reclassification.details.active.yes': 'Tak',
      'reclassification.details.active.no': 'Nie',
      'reclassification.details.payed': 'Zapłacone',
      'reclassification.details.submit': 'Przeklasyfikuj',
      'reclassification.details.error.reclassification-already-processed': 'Przeklasyfikowanie już wcześniej zostało zaimportowane',
      'reclassification.details.message.reclassification-processed': 'Przeklasyfikowanie zaimportowane',
      'reclassification.details.message.no.items': 'Brak oczekujących przeklasyfikowań',
      'reclassification.history.details.header.1': 'Przeklasyfikowanie nr ',
      'reclassification.history.details.header.2': ' z dn. ',
      'reclassification.history.details.header.3': ' zaimportowane dn. ',
      'reclassification.history.details.barcode': 'Kod kreskowy',
      'reclassification.history.details.hala': 'Hala',
      'reclassification.history.details.date': 'Data zbioru',
      'reclassification.history.details.beforeTypeName': 'Rodzaj przed przeklasyfikowaniem',
      'reclassification.history.details.afterTypeName': 'Rodzaj po przeklasyfikowaniu',
      'reclassification.history.details.remoteTypeName': 'Rodzaj ze skupu',
      'reclassification.history.details.pickerId': 'Id zbieraczki',
      'reclassification.history.details.pickerNr': 'Nr zbieraczki',
      'reclassification.history.details.pickerName': 'Imię i Nazwisko zbieraczki',
      'reclassification.history.details.pickerGroupName': 'Grupa',
      'reclassification.history.details.wagowy': 'Wagowy',
      'reclassification.history.details.massage': 'Uwagi',
      'reclassification.history.details.active': 'Włączone',
      'reclassify.header': 'Przeklasyfikowania',
      'reclassify.nr': 'Numer palety',
      'reclassify.type': 'Rodzaj',
      'reclassify.typeWeight': 'Waga jednostkowa',
      'reclassify.totalPcs': 'Ilość sztuk',
      'reclassify.totalWeight': 'Łączna waga',
      'reclassify.date': 'Data zbioru',
      'reclassify.chamber': 'Hala',
      'reclassify.subheader': 'Wybierz paletę by zmienić rodzaj grzybów lub halę',
      'reclassify.detail.header': 'Edycja palety nr ',
      'reclassify.detail.editType': 'Nowy rodzaj',
      'reclassify.detail.editCycle': 'Nowa hala',
      'reclassify.detail.barcode': 'Kod kreskowy',
      'reclassify.detail.picker.id': 'Id zbieraczki',
      'reclassify.detail.picker.name': 'Imię',
      'reclassify.detail.picker.surname': 'Nazwisko',
      'reclassify.detail.user.login': 'Skanujący',
      'reclassify.detail.trolleyMan':'Wagowy',
      'reclassify.detail.user.name': 'Imię',
      'reclassify.detail.user.surname': 'Nazwisko',
      'reclassify.detail.date': 'Data',
      'reclassify.detail.cycle': 'Hala',
      'reclassify.detail.submit': 'Zatwierdź',
      'reclassify.detail.deleteAll': 'Usuń paletę',
      'error.timeSheetNotClosed': 'Poprzedni okres zatrudnienia nie został zamknięty',
      'error.timeSheetClosed': 'Poprzedni okres zatrudnienia został zamknięty',
      'admin.users': 'Użytkownicy',
      'users.login': 'Login',
      'users.add-user.nonUniqueLogin': 'Podany login został już użyty',
      'users.name': 'Imię',
      'users.surname': 'Nazwisko',
      'users.panel': 'Technolog',
      'users.dostepy': 'Administracja',
      'users.rozliczenia': 'Płace',
      'users.waga': 'Wózkowy',
      'users.leader': 'Brygadzistka',
      'users.palety': 'Magazynier',
      'users.handlowiec':'Handlowiec',
      'users.hotel': 'Hotel',
      'users.newUser': 'Nowy użytkownik',
      'users.add-user.header': 'Nowy użytkownik',
      'users.add-user.username': 'Login',
      'users.add-user.name': 'Imię',
      'users.add-user.surname': 'Nazwisko',
      'users.add-user.password': 'Hasło',
      'users.add-user.access.panel': 'Technolog',
      'users.add-user.access.dostepy': 'Administracja',
      'users.add-user.access.rozliczenia': 'Płace',
      'users.add-user.access.waga': 'Wózkowy',
      'users.add-user.access.leader': 'Brygadzistka',
      'users.add-user.access.palety': 'Magazynier',
      'users.add-user.access.handlowiec': 'Handlowiec',
      'users.add-user.access.hotel': 'Hotel',
      'users.add-user.close': 'Anuluj',
      'users.add-user.save': 'Zapisz',
      'admin.reclassification': 'Przeklasyfikowania',
      'admin.reclassificationReport': 'Raport Przeklasyfikowań',
      'admin.order': 'Zamówienia',
      'admin.typeGroups': 'Grupy rodzai',
      'admin.typeGroup.breadcrumb.header': 'Grupy rodzai',
      'admin.typeGroup.create-button': 'Nowa grupa',
      'admin.typeGroup.create-modal-title': 'Nowa grupa rodzai',
      'admin.typeGroup.name': 'Nazwa',
      'admin.typeGroup.modal.cancel': 'anuluj',
      'admin.typeGroup.modal.save': 'dodaj',
      'admin.typeGroup.message.typeGroup-created': 'Grupa pomyślnie dodana',
      'admin.typeGroup.message.name-updated': 'Nazwa grupy zmieniona',
      'admin.typeGroup.message.deleted': 'Grupa usunięta',
      'admin.typeGroup.delete.header': 'Usunięcie grupy asortymentu',
      'admin.typeGroup.delete.prompt.message': 'Czy usunąć grupę: ',
      'admin.typeGroup.delete.prompt.cancel': 'Anuluj',
      'admin.typeGroup.delete.prompt.submit': 'Usuń',

      'admin.typeSize': 'Rozmiar grzybów',
      'admin.typeSize.breadcrumb.header': 'Rozmiar grzybów',
      'admin.typeSize.create-button': 'Nowy rozmiar',
      'admin.typeSize.create-modal-title': 'Nowy rozmiar',
      'admin.typeSize.name': 'Nazwa',
      'admin.typeSize.modal.cancel': 'anuluj',
      'admin.typeSize.modal.save': 'dodaj',
      'admin.typeSize.message.typeSize-created': 'Nowy rozmiar pomyślnie dodany',
      'admin.typeSize.message.name-updated': 'Nazwa rozmiaru zmieniona',
      'admin.typeSize.message.deleted': 'Rozmiar usunięty',
      'admin.typeSize.delete.header': 'Usunięcie rozmiaru',
      'admin.typeSize.delete.prompt.message': 'Czy usunąć rozmiar: ',
      'admin.typeSize.delete.prompt.cancel': 'Anuluj',
      'admin.typeSize.delete.prompt.submit': 'Usuń',

      'admin.box': 'Opakowania',
      'admin.box.breadcrumb.header': 'Opakowania',
      'admin.box.create-button': 'Nowe opakowanie',
      'admin.box.create-modal-title': 'Nowe opakowanie',
      'admin.box.name': 'Nazwa',
      'admin.box.modal.cancel': 'anuluj',
      'admin.box.modal.save': 'dodaj',
      'admin.box.message.typeGroup-created': 'Opakowanie pomyślnie dodane',
      'admin.box.message.name-updated': 'Nazwa opakowania zmieniona',
      'admin.box.message.deleted': 'Opakowanie usunięte',
      'admin.box.delete.header': 'Usunięcie opakowania',
      'admin.box.delete.prompt.message': 'Czy usunąć : ',
      'admin.box.delete.prompt.cancel': 'Anuluj',
      'admin.box.delete.prompt.submit': 'Usuń',

      'admin.trolleyMan':'Wagowi',
      'admin.trolleyMan.breadcrumb.header':'Wagowi',
      'admin.trolleyMan.create-button':'Nowy wagowy',
      'admin.trolleyMan.create-modal-title':'Nowy wagowy',
      'admin.trolleyMan.name':'Imię',
      'admin.trolleyMan.surname':'Nazwisko',
      'admin.trolleyMan.modal.cancel':'Anuluj',
      'admin.trolleyMan.modal.submit':'Utwórz',
      'admin.trolleyMan.modal.create.message.success':'Dodano nowego wagowego',
      'admin.trolleyMan.modal.update.message.success':'Zmiany pomyślnie zapisane',
      'admin.trolleyMan.barcode':'Kod kreskowy',

      'admin.type.breadcrumb.header': 'Rodzaje',
      'admin.type': 'Rodzaje',
      'admin.type.create.button': 'Nowy Typ',
      'admin.type.name': 'Nazwa',
      'admin.type.barcode': 'Kod kreskowy',
      'admin.type.weight': 'Waga',
      'admin.type.exportType': 'Export',
      'admin.type.group': 'Grupa',
      'admin.type.size': 'Rozmiar',
      'admin.type.box': 'Opakowanie',
      'admin.type.delete.header': 'Usunięcie rodzaju',
      'admin.type.delete.prompt.message': 'Czy usunąć rodzaj: ',
      'admin.type.delete.prompt.cancel': 'Anuluj',
      'admin.type.delete.prompt.submit': 'Usuń',
      'admin.type.create-modal-title': 'Nowy rodzaj',
      'admin.type.modal.cancel': 'Anuluj',
      'admin.type.modal.save': 'Dodaj',
      'admin.type.message.type-created': 'Nowy rodzaj pomyślnie utworzony',
      'admin.type.message.box-assigned': 'Opakowanie pomyślnie zmienione',
      'admin.type.message.group-assigned': 'Przypisano nową grupę',
      'admin.type.message.size-assigned': 'Przypisano nowy rozmiar',
      'admin.type.message.name-updated': 'Nazwa zmieniona',
      'admin.type.message.deleted': 'Rodzaj usunięty',
/*
      'massHarvest.header': 'Masowe wprowadzanie zbiorów',
      'massHarvest.nr': 'Nr',
      'massHarvest.name': 'Imię',
      'massHarvest.surname': 'Nazwisko',
      'massHarvest.amount': 'Ilość skrzyneczek',
      'massHarvest.weight': 'Łączna waga',
      'massHarvest.send': 'Zatwierdź',
      'massHarvest.total': 'Suma:',
      'massHarvest.message.success': 'Zbiór zatwierdzony',
      'massHarvest.message.error': 'Błąd zatwierdzania zbioru!',
      */
      'warehouse.acceptance.menu': 'Chmura',
      'warehouse.release.menu': 'Wysyłki',
      'warehouse.release.wz.menu': 'Dokumenty WZ',
      'warehouse.release.shipment.menu': 'Historia wysyłek',
      'warehouse.reclassification.menu': 'Przeklasyfikowania',
      'warehouse.change-palette.menu': 'Przesunięcia między paletami',
      'warehouse.status': 'Stan chłodni',
/*
      'warehouse.age': 'Wiek grzybów w chłodni',
      'waitingBoard.header': 'Oczekujące palety',
      'waitingBoard.header1': 'Wprowadź właściwą ilość skrzyneczek aby zaakceptować paletę, lub zwróć ją do wagowego.',
      'waitingBoard.nr': 'Numer palety',
      'waitingBoard.typeName': 'Rodzaj',
      'waitingBoard.typeWeight': 'Waga jednostkowa',
      'waitingBoard.cycle': 'Hala',
      'waitingBoard.scaleMan': 'Wagowy',
      'waitingBoard.amount': 'Ilość skrzyneczek',
      'waitingBoard.reject': 'Zwrot do wagowego',
      'warehouse.breadcrumb.wzList': 'Lista WZ',
      'warehouse.breadcrumb.wzDetails': 'Dokument WZ',
      'warehouse.status.header': 'Stany chłodni',
      'warehouse.status.total': 'Suma',
      'warehouse.status.trolley': 'Wagi',
      'warehouse.status.pcs': 'sztuk',
      'warehouse-age.status.header': 'Wiek grzybów w chłodni',
      'warehouse-age.status.typeName': 'Rodzaj',
      'warehouse-age.status.typeWeight': 'Waga',
      'warehouse-age.status.total': 'Suma',
      'warehouse.outgo': 'Wydanie zewnętrzne',
      'warehouse.wz': 'Dokumenty WZ',
      'warehouse.wz.summary.header': 'Lista dokumentów WZ',
      'warehouse.wz.summary.no': 'Numer',
      'warehouse.wz.summary.date': 'Data',
      'warehouse.wz.summary.customer': 'Odbiorca',
      'warehouse.wz.summary.creatorLogin': 'Wystawiający',
      'warehouse.wz.summary.creatorName': 'Imię',
      'warehouse.wz.summary.creatorSurname': 'Nazwisko',
      'warehouse.wz.summary.amount': 'Ilość sztuk',
      'warehouse.wz.summary.weight': 'Łączna waga',
      'warehouse.wz.detail.header': 'Dokument WZ nr:',
      'warehouse.wz.detail.customer': 'Nabywca:',
      'warehouse.wz.detail.description': 'Opis',
      'warehouse.wz.detail.date': 'Data wydania:',
      'warehouse.wz.detail.user': 'Wydający:',
      'warehouse.wz.detail.position': 'Pozycja',
      'warehouse.wz.detail.typeName': 'Rodzaj',
      'warehouse.wz.detail.typeWeight': 'Waga jednostkowa',
      'warehouse.wz.detail.totalAmount': 'Ilość sztuk',
      'warehouse.wz.detail.totalWeight': 'Suma kilogramów',
      'warehouse.wz.detail.total': 'Suma:',
      'warehouse.wz.detail.paletteName': 'Nazwa palety',
      'warehouse.wz.detail.paletteAmount': 'Ilość',
      'warehouse.wz.detail.price': 'Cena',
      'warehouse.wz.detail.release-time': 'Okres załadunku',


      'warehouse.brcByDate': 'Raport BRC wg dat',
      'warehouse.brcByBarcode': 'Raport BRC dla kodu',
      'warehouse.findBarcode': 'Znajdź skrzyneczkę',
      'warehouse.findBarcodeByDate': 'Znajdź skrzyneczkę wg daty',
      'warehouse.find.barcode.message.not-a-digit': 'Proszę wprowadzać jedynie cyfry',
      'warehouse.find.barcode.message.invalid-supplier': 'Niewłaściwy kod pieczarkarnii',
      'warehouse.find.barcode.message.not-on-stock': 'Brak kodu w historii',
      'warehouse.reclassification': 'Przeklasyfikowania skrzyneczek',
      'warehouse.brcByDate.warehouseStock': 'Pozycje na chłodni',
      'warehouse.brcByDate.sold': 'Pozycje na dokumentach WZ',
      'warehouse.brcByDate.typeName': 'Rodzaj',
      'warehouse.brcByDate.typeWeight': 'Waga jednostkowa',
      'warehouse.brcByDate.chamber': 'Hala',
      'warehouse.brcByDate.depotName': 'Chłodnia',
      'warehouse.brcByDate.totalAmount': 'Ilość sztuk',
      'warehouse.brcByDate.totalWeight': 'Łączna waga',
      'warehouse.brcByDate.customerName': 'Odbiorca',
      'warehouse.brcByDate.wzNr': 'Numer dokumentu WZ',
      'warehouse.brcByDate.transactionDate': 'Data wydania',
      'warehouse.brcByDate.detail.barcode': 'Kod kreskowy',
      'warehouse.brcByDate.detail.typeName': 'Rodzaj',
      'warehouse.brcByDate.detail.typeWeight': 'Waga jednostkowa',
      'warehouse.brcByDate.detail.pickerName': 'Zbieraczka imię',
      'warehouse.brcByDate.detail.pickerSurname': 'Nazwisko',
      'warehouse.brcByDate.detail.harvestDate': 'Data Zbioru',
      'warehouse.brcByDate.breadcrumb.summary': 'BRC podsumowanie',
      'warehouse.brcByDate.breadcrumb.warehouse.details': 'BRC lista szczegółowa stanu chłodni',
      'warehouse.brcByDate.breadcrumb.wz.details': 'BRC lista szczegółowa WZ',
      'warehouse.brcByBarcode.header': 'Informacje o kodzie kreskowym oraz pozostałych zbiorach tego samego dnia w tej samej hali',
      'warehouse.brcByBarcode.barcodeHeader': 'Poszukiwana skrzyneczka:',
      'warehouse.brcByBarcode.barcopde': 'kod:',
      'warehouse.brcByBarcode.typeName': 'rodzaj:',
      'warehouse.brcByBarcode.typeWeight': 'waga:',
      'warehouse.brcByBarcode.pickerName': 'imię:',
      'warehouse.brcByBarcode.pickerSurname': 'nazwisko:',
      'warehouse.brcByBarcode.harvestDate': 'data zbioru:',
      'warehouse.brcByBarcode.halaName': 'hala:',
      'warehouse.brcByBarcode.wzId': 'wz nr:',
      'warehouse.brcByBarcode.paletteId': 'paleta nr:',
      'warehouse.brcByBarcode.customerName': 'odbiorca:',
      'warehouse.brcByBarcode.wzDate': 'data sprzedaży:',
      'warehouse.brcByBarcode.depotName': 'chłodnia:',
      'warehouse.brcByBarcode.breadcrumb.summary': 'BRC podsumowanie dla kodu',
      'warehouse.brcByBarcode.breadcrumb.warehouse.details': 'BRC lista szczegółowa stanu chłodni',
      'warehouse.brcByBarcode.breadcrumb.wz.details': 'BRC lista szczegółowa WZ',
      'warehouse.outgo.release.message.invalid-prefix': 'Niewłaściwy kod palety',
      'warehouse.outgo.release.message.not.digit': 'Proszę wprowadzać jedynie liczby',
      'warehouse.outgo.release.message.palette-released': 'Paleta została już wcześniej wprowadzona.',
      'warehouse.outgo.release.message.palette-not-found': 'Nie znaleziono palety o numerze:',
      'warehouse.outgo.release.submit': 'Generuj dokument WZ',
      'warehouse.outgo.breadcrumb.summary': 'Oczekujące zamówienia',
      'warehouse.outgo.breadcrumb.details': 'Wysyłka',
      'warehouse.outgo.breadcrumb.wz': 'WZ',
      'warehouse.outgo.breadcrumb.delivery-letter': 'Kolejność palet',
      'warehouse.findBarcode.date.placeholder': 'Data zbioru',
      'warehouse.findBarcode.cycle': 'Hala',
      'warehouse.findBarcode.message.notADigit': 'Niewłaściwa wartość. Proszę wprowadzać jedynie cyfry.',
      'warehouse.findBarcode.message.invalidSupplier': 'Niewłaściwy kod pieczarkarni.',
      'warehouse.findBarcode.message.noHarvestDate': 'Proszę wybrać datę zbioru.',
      'warehouse.findBarcode.message.noCycle': 'Proszę wybrać halę.',
      'warehouse.findBarcode.message.notOnStock': 'Pozycja nie istnieje w magazynie.',
      'warehouse.findBarcode.message.typeName': 'Rodzaj:',
      'warehouse.findBarcode.message.typeWeight': 'Waga:',
      'warehouse.findBarcode.message.chamber': 'Hala:',
      'warehouse.findBarcode.message.harvestDate': 'Data Zbioru:',
      'warehouse.findBarcode.message.picker': 'Zbieraczka:',
      'warehouse.reclassifyByBarcode.type': 'Rodzaj',
      'warehouse.reclassifyByBarcode.reason': 'Przyczyna',
      'warehouse.reclassifyByBarcode.message.submit': 'Przeklasyfikuj',
      'warehouse.reclassifyByBarcode.message.cancel': 'Anuluj',
      'warehouse.reclassifyByBarcode.message.reserved1': 'Skrzyneczka jest zarezerwowana, zamówienie nr: ',
      'warehouse.reclassifyByBarcode.message.reserved2': ' paleta nr: ',
      'warehouse.reclassifyByBarcode.message.unknownError': 'Coś poszło nie tak',
      'warehouse.reclassifyByBarcode.message.notOnStock': 'Brak pozycji w stanach magazynowych',
      'warehouse.reclassifyByBarcode.message.notADigit': 'Proszę wprowadzać jedynie cyfry',
      'warehouse.reclassifyByBarcode.message.invalidSupplier': 'Niewłaściwy kod pieczarkarni',
      'warehouse.reclassifyByBarcode.message.success': 'Przeklasyfikowanie pomyślnie zakończone.',
      'warehouse.reclassifyByBarcode.warehouse-only': 'Tylko magazyn',
      'warehouse.reclassifyByBarcode.quality-check': 'Kontrola jakości',
      'warehouse.reclassifyByBarcode.barcode': 'Kod kreskowy',
      'warehouse.reclassifyByBarcode.typeName': 'Rodzaj',
      'warehouse.reclassifyByBarcode.typeWeight': 'Waga',
      'warehouse.reclassifyByBarcode.harvestDate': 'Data zbioru',
      'warehouse.reclassifyByBarcode.chamberName': "Hala",
      'warehouse.reclassifyByBarcode.pickerId': 'Id zbieraczki',
      'warehouse.reclassifyByBarcode.pickerName': 'Imię',
      'warehouse.reclassifyByBarcode.pickerSurname': 'Nazwisko',
      'warehouse.reclassifyByBarcode.breadcrumb.main': 'Przeklasyfikowania pojedyńczych skrzyneczek',
 */
      'payroll.calendar': 'Kalendarz',
      'payroll.sunday': 'Niedziela',
      'payroll.bonusDay': 'Święto',
      'payroll.monday': 'Poniedziałek',
      'payroll.tuesday': 'Wtorek',
      'payroll.wednesday': 'Środa',
      'payroll.thursday': 'Czwartek',
      'payroll.friday': 'Piątek',
      'payroll.saturday': 'Sobota',
      'payroll.wages': 'Stawki akordowe',
      'payroll.people.wages': 'Stawki pracowników',
      'payroll.people.bonus-types': 'Dodatki płacowe',
      'payroll.people.wages.hourly': 'Czas',
      'payroll.people.wages.accord': 'Akord',
      'payroll.people.wages.person': 'Pracownik',
      'payroll.people.wages.breadcrumb': 'Stawki pracowników',
      'payroll.people.wages.payrollType': 'Typ',
      'payroll.people.wages.regularWage': 'Dni powszednie',
      'payroll.people.wages.sundayWage': 'Niedziele',
      'payroll.people.wages.bonusWage': 'Święta',
      'payroll.people.wages.message.wage-updated': 'Stawka godzinowa pomyślnie zmieniona',
      'payroll.people.wages.message.payrollType-updated': 'Type rozliczenia pomyślnie zmieniony',
      'payroll.bonus.main.breadcrumb': 'Dodatki płacowe',
      'payroll.bonus.add-fixed-bonus-button': 'Nowy dodatek kwotowy',
      'payroll.bonus.add-percent-bonus-button': 'Nowy dodatek procentowy',
      'payroll.bonus.add-fixed-modal-title': 'Nowy dodatek kwotowy',
      'payroll.bonus.add-fixed-modal-name': 'Nazwa',
      'payroll.bonus.add-fixed-modal-value': 'Kwota',
      'payroll.bonus.add-fixed-modal-cancel': 'Anuluj',
      'payroll.bonus.add-fixed-modal-submit': 'Dodaj',
      'payroll.bonus.currency': 'PLN',
      'payroll.bonus.name': 'Nazwa',
      'payroll.bonus.param': 'Wartość',
      'payroll.bonus.add-percentage-modal-title': 'Nowy dodatek procentowy',
      'payroll.bonus.add-percentage-modal-name': 'Nazwa',
      'payroll.bonus.add-percentage-modal-value': 'Procent',
      'payroll.bonus.add-percentage-modal-cancel': 'Anuluj',
      'payroll.bonus.add-percentage-modal-submit': 'Dodaj',
      'payroll.bonus.add-message.success': 'Nowy dodatek płacowy utworzony z powodzeniem',
      'payroll.bonus.remove-message.success': 'Dodatek pomyślnie usunięty',
      'payroll.bonus.delete.header': 'Usunięcie dodatku',
      'payroll.bonus.delete.prompt.message': 'Czy usunąć dodatek',
      'payroll.bonus.delete.prompt.message2': 'o wysokości ',
      'payroll.bonus.delete.cancel': 'Anuluj',
      'payroll.bonus.delete.submit': 'Usuń',
      'payroll.accounts': 'Stan kont',
      'payroll.salary.account.status.personId': 'Id',
      'payroll.salary.account.status.personNr': 'Nr',
      'payroll.salary.account.status.personName': 'Imię',
      'payroll.salary.account.status.personSurname': 'Nazwisko',
      'payroll.salary.account.status.amount': 'Stan konta',
      'payroll.salary.account.status.payoff-button': 'Wypłata',
      'payroll.salary.account.status.payment-button': 'Wpłata',
      'payroll.salary.account.modal.header': 'Wypłata z konta',
      'payroll.salary.account.payoff.modal.message': 'Wypłata dla ',
      'payroll.salary.account.payoff.modal.cancel': 'Anuluj',
      'payroll.salary.account.payoff.modal.submit': 'Wypłata',
      'payroll.salary.account.status.breadcrumb.header': 'Stan kont',
      'payroll.salary.account.status.breadcrumb.history': 'Historia konta',
      'payroll.salary.account.message.payoff.success': 'Wypłata pomyślnie zapisana',
      'payroll.salary.account.message.payment.success': 'Wpłata pomyślnie zapisana',
      'payroll.salary.history.creator': 'Wprowadzający',
      'payroll.salary.history.date': 'Data',
      'payroll.salary.history.amount': 'Kwota',
      'payroll.salary.history.total': 'Suma',
      'payroll.salary.message.payroll-type-not-set': 'Proszę ustawić typ rozliczenia: akord bądź godzinowy dla pracownika id: ',
      'payroll.salary.message.payroll-null-work-date': 'Niezamknięty okres pracy dla pracownika id:',
      'payroll.salary': 'Lista płac',
      'wages.type': 'Rodzaj',
      'wages.typeWeight': 'Waga netto',
      'wages.regular': 'Stawka za dni powszednie',
      'wages.sunday': 'Stawka niedzielna',
      'wages.bonus': 'Stawka świąteczna',
      'wage.breadcrumb.wage': 'Lista stawek akorowych',
      'wage.breadcrumb.wageDetails': 'Edycja stawki',
      'wages.detail.header': 'Edycja stawek dla ',
      'wages.detail.startDate': 'Data początkowa',
      'wages.detail.regular': 'Powszednie',
      'wages.detail.sunday': 'Niedziele',
      'wages.detail.bonus': 'Święta',
      'wages.detail.validation.error': 'Wprowadzono niewłaściwą wartość dla stawki. Proszę wprowadzać jedynie liczby.',
      'wages.detail.submit': 'Dodaj stawkę',
      'wages.name': 'Nazwa',
      'wages.cancel': 'Anuluj',
      'wages.message.wage-updated': 'Stawka pomyślnie zmieniona.',
      'wages.message.wage-header-created': 'Dodano nową grupę stawek',
      'salary.personNr': 'Nr',
      'salary.personId': 'Id',
      'salary.personName': 'Imię',
      'salary.personSurname': 'Nazwisko',
      'salary.groupName': 'Grupa',
      'salary.summary': 'Suma',
      'salary.summary.plus.percentage.bonus.total':'Suma z dodatkami procentowymi',
      'salary.quality': 'Jakość',
      'salary.workingDaysAmount':'Ilość dni pracy',
      'salary.totalKg': 'Suma zbioru',
      'salary.workTime': 'Czas pracy',
      'salary.workTimeSalary': 'Zarobki godzinowe',
      'salary.regularSalary': 'Dni powszednie',
      'salary.sundaySalary': 'Niedziele',
      'salary.bonusSalary': 'Święta',
      'salary.startDate': 'Początek',
      'salary.endDate': 'Koniec',
      'salary.closeMonth': 'Zamknięcie miesiąca',

      'salary.breadcrumb.main': 'Listy płac',
      'salary.breadcrumb.person-details': 'Rozliczenie miesięczne ',
      'salary.payed.person.detail.type-name': 'Rodzaj',
      'salary.payed.person.detail.regular-days': 'Dni powszednie',
      'salary.payed.person.detail.sundays': 'Niedziele',
      'salary.payed.person.detail.bonus-days': 'Święta',
      'salary.payed.person.detail.kg-amount': 'Ilość kilogramów',
      'salary.payed.person.detail.wage': 'Stawka za kilogram',
      'salary.payed.person.detail.money-amount': 'Kwota',
      'salary.payed.person.detail.total': 'Suma',
      'salary.payed.person.detail.harvest-total': 'Suma zbiorów:',
      'salary.payed.person.detail.bonus-total': 'Suma dodatków:',
      'salary.payed.person.detail.bonus-name': 'Dodatki płacowe',
      'salary.payed.person.detail.bonus-amount': 'Wartość',
      'salary.payed.person.detail.total-salary': 'Wynagrodzenie łącznie: ',
      'salary.payed.person.message1': 'Rozliczenie dla ',
      'salary.payed.person.message2': ' za okres ',
      'salary.payed.person.detail.day':'Dzień',
      'salary.payed.person.detail.worktime':'Czas pracy',


/*
      'order-admin.create-button': 'Nowe zamówienie',
      'order-admin.order.nr': 'Zamówienie numer',
      'order-admin.customer': 'Odbiorca',
      'order-admin.creator': 'Twórca zamówienia:',
      'order-admin.creationDate': 'Data utworzenia',
      'order-admin.releaseDate': 'Data dostawy',
      'order-admin.plate': 'Tablica',
      'order-admin.description': 'Uwagi',
      'order-admin.palette.nr': 'Paleta numer',
      'order-admin.typeName': 'Rodzaj',
      'order-admin.typeWeight': 'Waga jednostkowa',
      'order-admin.totalWeight': 'Łączna waga',
      'order-admin.totalAmount': 'Ilość zamówionych sztuk',
      'order-admin.preparedAmount': 'Ilość przygotowanych sztuk',
      'order-admin.price': 'Cena',
      'order-admin.tooltip.publish': 'Udostępnij zamówienie do realizacji',
      'order-admin.tooltip.unpublish': 'Cofnij udostępnienie zamówienia',
      'order-admin.tooltip.unprepare': 'Cofinij gotowość do wysyłki',
      'order-admin.tooltip.delete': 'Usuń zamówienie',
      'order-admin.tooltip.edit': 'Edycja zamówienia',
      'order-admin.tooltip.printPaletteLabel': 'Wydrukuj etykietę palety',
      'order-admin.message.boxes-assigned': 'Nie można zmienić stanu tego zamówienia, bo są do niego już przypisane <grzyby.',
      'order-admin.message.undefined-error': 'Coś poszło nie tak.',
      'order-admin.breadcrumb.summary': 'Lista zamówień',
      'order-admin.breadcrumb.create': 'Nowe zamówienie',
      'order-admin.breadcrumb.edit': 'Edycja zamówienia nr ',
      'order-admin.breadcrumb.delivery-letter': 'Kolejność palet',
      'order-edit.addPalette': 'Dodaj paletę',
      'order-edit.deletePalette': 'Usuń zamówienie',
      'order-edit.movePalette': 'Przenieś paletę do innego zamówienia',
      'order-edit.add-palette.modal.header': 'Dodaj paletę',
      'order-edit.add-palette.modal.type': 'Rodzaj',
      'order-edit.add-palette.modal.amount': 'Ilość szt.',
      'order-edit.add-palette.modal.cancel': 'Anuluj',
      'order-edit.add-palette.modal.submit': 'Zapisz',


      'order-edit.price': 'Cena',

      'order-edit.add-palette.modal.price': 'Cena za kg.',
      'order-edit.add-palette.modal.currency': 'Waluta',

      'order-edit.button.delivery-letter': 'Kolejność palet',
      'order-edit.message.to.low': 'Ilość nie może być niższa od aktualnie zeskanowanej',
      'order-edit.message.order.amount.updated': 'Ilość zamówienia zmieniona',
      'order-edit.message.order.price.updated': 'Cena zmieniona',
      'order-edit.message.order.currency.updated': 'Waluta zmieniona',
      'order-edit.message.order.truck.updated': 'Samochód zmieniony',

      'delivery-letter.id': 'Opis załadunku nr',
      'delivery-letter.plate': 'Tablica rejestracyjna',
      'delivery-letter.position': 'Pozycja',
      'delivery-letter.release-date': 'Data wysyłki',
      'delivery-letter.palette-id': 'Numer palety',
      'delivery-letter.order-id': 'Numer zamówienia',
      'delivery-letter.customer': 'Odbiorca',
      'delivery-letter.success-message': 'Kolejność palet zmieniona',

      'create-order.deleteButton': 'Cofnij rezerwację',
      'create-order.customer': 'Odbiorca',
      'create-order.required': 'Data dostawy',
      'create-order.truck': 'Samochód',
      'create-order.description': 'Uwagi',
      'create-order.add-palette': 'Dodaj paletę',
      'create-order.add-batch': 'Dodaj typ grzybów do palety',
      'create-order.create': 'Zapisz zamówienie',
      'create-order.barcode': 'Kod kreskowy',
      'create-order.typeName': 'Rodzaj',
      'create-order.typeWeight': 'Waga',
      'create-order.delete': 'Usuń',
      'create-order.message.barcode.reserved': 'Kod został wcześniej zarezerwowany.',
      'create-order.message.batch.fully.reserved': 'Brak rezerwacji dla wprowadzonego rodzaju.',
      'create-order.message.no.such.code': 'Wprowadzony kod nie znaleziony na magazynie.',
      'create-order.message.not.digit': 'Proszę wprowadzać jedynie liczby',
      'create-order.message.choose.palette': 'Proszę wybrać paletę',
      'create-order.message.invalid.prefix': 'Niewłaściwy kod pieczarkarni',
      'create-order.breadcrumb.menu': 'Podsumowanie zamówień',
      'create-order.breadcrumb.details': 'Kompletacja palety',
      'create-order.placeholder.amount': 'Ilość',
      'create-order.placeholder.price': 'Cena',
      'prepare-order.tooltip.complete': 'Oznacz jako zrealizowane',
*/


      'settings.reclassifyReason': 'Przyczyny przeklasyfikowań',
      'settings.reclassifyReason.addButton': 'Dodaj',
      'settings.reclassifyReason.add-reason-modal.header': 'Dodaj przyczynę przeklasyfikowania',
      'settings.reclassifyReason.add-reason-modal.cancel': 'Anuluj',
      'settings.reclassifyReason.add-reason-modal.submit': 'Dodaj',
      'settings.reclassifyReason.reason': 'Opis',
      'settings.truck.menu': 'Samochody',
      'settings.truck.create.button': 'Nowy samochód',
      'settings.truck.add': 'Dodaj samochód',
      'settings.truck.plate': 'Tablica rejestracyjna',
      'settings.truck.description': 'Opis',
      'settings.truck.capacity': 'Ilość palet',
      'settings.truck.message.truck-created': 'Samochód dodany z powodzeniem',
      'settings.truck.message.plate-exists': 'Tablica rejestracyjna już została użyta dla innego samochodu',
      'settings.truck.message.truck.deleted': 'Samochód pomyślnie usunięty',
      'settings.customer.menu': 'Odbiorcy',
      'settings.customer.create-button': 'Nowy klient',
      'settings.customer.name': 'Nazwa',
      'settings.customer.address': 'Adres',
      'settings.customer.modal.save': 'Zapisz',
      'settings.customer.modal.cancel': 'Anuluj',
      'settings.customer.edit-modal-title': 'Edycja danych klienta',
      'settings.customer.delete.header': 'Usunięcie Klienta',
      'settings.customer.delete.prompt.message': 'Czy usunąć klienta ',
      'settings.customer.delete.prompt.cancel': 'Anuluj',
      'settings.customer.delete.prompt.submit': 'Usuń',
      'settings.customer.message.customer.updated': 'Dane klienta zmienione.',
      'settings.customer.message.customer.created': 'Nowy klient pomyślnie dodany.',
      'settings.customer.message.customer.deleted': 'Klient usunięty.',
      'settings.currency': 'Waluty',
      'settings.company': 'Dane firmy',
      'settings.company.create':'Nowa firma',
      'settings.company.create-button':'Nowa firma',
      'settings.company.edit': 'Dane firmy',
      'settings.company.menu': 'Dane firmy',
      'settings.company.name': 'Nazwa',
      'settings.company.street': 'Ulica',
      'settings.company.city': 'Miejscowość',
      'settings.company.nip': 'NIP',
      'settings.company.regon': 'REGON',
      'settings.company.phoneNo': 'Telefon',
      'settings.company.email': 'Email',
      'settings.company.ggn': 'Numer GGN',
      'settings.company.button.update': 'Zapisz',
      'settings.company.message.success': 'Dane pomyślnie zmienione',
      'settings.depot': 'Chłodnie',
      'settings.depot.create-button': 'Dodaj chłodnię',
      'settings.depot.bradcrump.header': 'Chłodnie',
      'settings.depot.message.depot-created': 'Chłodnia dodana',
      'settings.depot.message.name-updated': 'Nazwa chłodni zmieniona',
      'settings.depot.create-modal-title': 'Dodaj chłodnię',
      'settings.depot.name': 'Nazwa',
      'settings.depot.modal.cancel': 'Anuluj',
      'settings.depot.modal.save': 'Dodaj',
      'settings.chamber': 'Hale',
      'settings.chamber.bradcrump.header': 'Hale uprawowe',
      'settings.chamber.name': 'Nazwa',
      'settings.chamber.area': 'Powierzchnia',
      'settings.chamber.depot': 'Chłodnia',
      'settings.chamber.company':'Firma',
      'settings.chamber.create-button': 'Dodaj halę',
      'settings.chamber.create.header': 'Dodaj halę',
      'settings.chamber.create.name': 'Nazwa',
      'settings.chamber.create.area': 'Powierzchnia',
      'settings.chamber.create.depot': 'Chłodnia',
      'settings.chamber.create.company':'Firma',
      'settings.chamber.create.prompt.cancel': 'Anuluj',
      'settings.chamber.create.prompt.submit': 'Dodaj',
      'settings.chamber.delete.header': 'Usunięcie hali',
      'settings.chamber.delete.prompt.message': 'Czy usunąć ',
      'settings.chamber.delete.prompt.cancel': 'Anuluj',
      'settings.chamber.delete.prompt.submit': "Usuń",
      'settings.chamber.message-depot.updated': "Chłodnia zmieniona",
      'settings.chamber.message-company.updated':'Firma zmieniona',
      "settings.chamber.message-name.updated": "Nazwa hali zmieniona",
      "settings.chamber.message-area.updated": "Powierzchnia hali zmieniona",
      "settings.chamber.message-chamber.deleted": "Hala usunięta",
      "settings.chamber.message-chamber.created": "Hala utworzona",

      "settings.subsoil": "Kompost",
      'settings.subsoil.create-button': 'Dodaj nowy typ kompostu',
      'settings.subsoil.bradcrump.header': 'Typy kompostu',
      'settings.subsoil.message.subsoil-created': 'Kompost dodany',
      'settings.subsoil.message.subsoil.deleted': 'Kompost usunięty',
      'settings.subsoil.message.name-updated': 'Nazwa kompostu zmieniona',
      'settings.subsoil.create-modal-title': 'Dodaj typ kompostu',
      'settings.subsoil.name': 'Nazwa',
      'settings.subsoil.modal.cancel': 'Anuluj',
      'settings.subsoil.modal.save': 'Dodaj',

      "settings.mycelium": "Grzybnia",
      "settings.mycelium.create-button": "Dodaj nowy typ grzybni",
      "settings.mycelium.bradcrump.header": "Typy grzybni",
      "settings.mycelium.message.mycelium-created": "Grzybnia dodana",
      "settings.mycelium.message.mycelium.deleted": "Grzybnia usunięta",
      "settings.mycelium.message.name-updated": "Nazwa grzybni zmieniona",
      "settings.mycelium.create-modal-title": "Dodaj grzybnię",
      "settings.mycelium.name": "Nazwa",
      "settings.mycelium.modal.cancel": "Anuluj",
      "settings.mycelium.modal.save": "Dodaj",


      'all': 'Wszystkie waluty',
      'active': 'Aktywne waluty',
      'audit.localReclassification.header': 'Raport przeklasyfikowań',
      'audit.localReclassification.barcode': 'Kod kreskowy',
      'audit.localReclassification.date': 'Data',
      'audit.localReclassification.picker': 'Zbieraczka',
      'audit.localReclassification.user': 'Użytkownik',
      'audit.localReclassification.sourceType': 'Rodzaj źródłowy',
      'audit.localReclassification.targetType': 'Rodzaj docelowy',
      'audit.localReclassification.sourceChamber': 'Hala źródłowa',
      'audit.localReclassification.targetChamber': 'Hala docelowa',
      'audit.localReclassification.reason': 'Opis',
      'create-order-remove-reservation.submit': 'Usuń rezerwacje',
      'create-order-remove-reservation.cancel': 'Anuluj',
      'create-order-remove-reservation.breadcrumb.menu': 'Podsumowanie zamówień',
      'create-order-remove-reservation.breadcrumb.remove': 'Usuwanie rezerwacji',
      'create-order-remove-reservation.message.notADigit': 'Proszę wprowadzać jedynie cyfry.',
      'create-order-remove-reservation.message.notReserved': 'Pozycja nie jest zarezerwowana',
      'create-order-remove-reservation.message.notExists': 'Pozycja nie istnieje w stanach magazynowych',
      'create-order-remove-reservation.message.success': 'Rezerwacje pomyślnie usunięte',
      'create-order-remove-reservation.message.alreadyScanned': 'Pozycja zeskanowana powtórnie',
      'create-order-remove-reservation.barcode': 'Kod kreskowy',
      'create-order-remove-reservation.type': 'Rodzaj',
      'create-order-remove-reservation.customer': 'Odbiorca',
      'create-order-remove-reservation.order': 'Numer zamówienia',
      'create-order-remove-reservation.palette': 'Numer palety',
      'workTime.report.id': 'Id',
      'workTime.report.nr': 'Nr',
      'workTime.report.name': 'Imię',
      'workTime.report.surname': 'Nazwisko',


      'order-report.breadcrumb.headers': 'Raport zamówień',

      'order-report.breadcrumb.details': 'Szczegóły zamówienia',
      'order-report.orderId': 'Numer zamówienia',
      'order-report.customerName': 'Odbiorca',
      'order-report.customerAddress': 'Adres',
      'order-report.requiredDate': 'Data zamówienia',
      'order-report.releaseDate': 'Data wysyłki',
      'order-report.harvestDate': 'Data zbioru',
      'order-report.wzNr': 'Numer WZ',
      'order-report.palettesAmount': 'Ilość palet',
      'order-report.barcode': 'Kod kreskowy',
      'order-report.pickerId': 'Id',
      'order-report.pickerNr': 'Nr',
      'order-report.pickerName': 'Imię',
      'order-report.pickerSurname': 'Nazwisko',
      'order-report.chamberName': 'Hala',
      'order-report.typeName': 'Rodzaj',
      'order-report.typeWeight': 'Waga',
      'order-report.paletteId': 'Numer palety',

      'cycles.dates': 'Daty cykli',
      'cycles.headers': 'Wyniki w halach',
      'cycle.list.chamberName': "Hala",
      'cycle.list.startDate': "Początek",
      'cycle.list.endDate': "Koniec",
      'cycle.list.total': "Suma",
      'cycle.list.quality': "Jakość",
      'cycle.list.amountPerMeter': "kg/metr",
      'cycle.list.amountPerTon': "kg/tona",
      'cycle.list.dryAmount': "kg/tona sm.",
      'cycle.list.humidity': "Wilgotność",
      'cycle.list.area': "Powierzchnia",
      'cycle.list.weight': "Masa kompostu",
      'cycle.list.subsoilName': "Kompostownia",
      'cycle.list.myceliumName': "Grzybnia",
      'cycle.list.technologist': "Technolog",
      'cycle.list.avgDailyHarvest': 'Średnia dzienna',
      'cycle.list.kg': 'kg',
      'cycle.list.meter': 'm',
      'cycle.list.ton': 't',
      'cycle.list.percent': '%',
      'cycle.list.kg.per.sqr.mtr': 'kg/m',
      'cycle.list.kg.per.ton': "kg/t.",
      'cycle.list.kg.per.dry.ton': "kg/t. sm",
      'cycle.list.kg.per.day': "kg/dn.",

      'cycle.dates.header': 'Daty cykli',
      'cycle.dates.breadcrumb.dates': 'Daty cykli',
      'cycle.dates.breadcrumb.cycles-summary': 'Podsumowanie cykli',
      'cycle.dates.breadcrumb.cycles-details': 'Szczegóły cyklu',
      'cycle.dates.chamberName': 'Hala',
      'cycle.dates.init':'Założenie',
      'cycle.dates.startFirstPeriod': 'Początek I rzutu',
      'cycle.dates.startSecondPeriod': 'Początek II rzutu',
      'cycle.dates.startThirdPeriod': 'Początek III rzutu',
      'cycle.dates.end': '',
      'cycle.dates.area': 'Powierzchnia m',
      'cycle.dates.weight': 'Ilość kg. podłoża',
      'cycle.dates.humidity': 'Wilgotność podłoża',
      'cycle.dates.mycelium': 'Grzybnia',
      'cycle.dates.subsoil': 'Kompost',
      'cycle.dates.technologist': 'Prowadzący',
      'cycle.dates.message.cycle-updated': 'Dane cyklu pomyślnie zmienione',
      'cycle.dates.message.cycle-closed': 'Cykl został pomyślnie zamknięty',
      'cycle.dates.message.startSecondPeriod-before-startDate': 'Początek drugiego rzutu nie może zostać ustawiony przed rozpoczęciem cyklu',
      'cycle.dates.message.startThirdPeriod-before-startSecondPeriod': 'Początek trzeciego rzutu nie może zostać ustawiony przed rozpoczęciem drugiego.',
      'cycle.dates.message.startSecondPeriod-after-startThirdPeriod': 'Początek drugiego rzutu nie może zostać ustawiony po dacie rozpoczęcie trzeciego',
      'cycle.dates.message.area.below.zero': 'Powierzchnia uprawy powinna być większa od zera',
      'cycle.dates.message.weight.below.zero': 'Waga podłoża powinna być większa niż zero.',
      'cycle.dates.message.weight.invalid.humidity': 'Wilgotność podłoża powinna zawierać się pomiędzy 0 a 100',
      'cycle.dates.message.first-day.after-harvest': 'Data rozpoczęcia cyklu późniejsza niż data pierwszego zbioru: ',
      'cycle.dates.message.startDate-after-startFirstPeriod': 'Data rozpoczęcia późniejsza niż data rozpoczęcia pierwszego rzutu',
      'cycle.dates.message.cycle-created': 'Cykl pomyślnie utworzony',
      'cycle.dates.message.startFirstPeriod-before-startDate':'Data rozpoczęcia pierwszego rzutu przed datą rozpoczęcia cyklu',
      'cycle.dates.message.startFirstPeriod-after-startSecondPeriod':'Pierwszy rzut nie może rozpoczynać się po dacie rozpoczęcia drugiego rzutu.',
      'cycle.dates.message.startDate-after-startSecondPeriod':'Data rozpoczęcia cyklu późniejsza niż data rozpoczęcia pierwszego rzutu.',
      'cycle.dates.close.header': 'Zamknięcie cyklu',
      'cycle.dates.close.prompt.message': 'Czy zamknąć cykl dla ',
      'cycle.dates.close.prompt.cancel': 'Anuluj',
      'cycle.dates.close.prompt.submit': 'Zamknij',
      'cycle.closeCycle.button': 'Zakończ cykl',
      'cycle.details.cycleSummary': 'Sumy cyklu',
      'cycle.details.thirdPeriodSummary': 'Trzeci rzut',
      'cycle.details.secondPeriodSummary': 'Drugi rzut',
      'cycle.details.firstPeriodSummary': 'Pierwszy rzut',
      'cycle.details.day': 'Data',
      'cycle.details.inne': 'Inne',
      'cycle.details.kraj': 'Kraj',
      'cycle.details.export': 'Eksport',
      'cycle.details.total': 'Suma',
      'cycle.details.quality': 'Jakość',
      'cycle.details.kgM': 'kg/m',
      'cycle.details.kgT': 'kg/t',
      'cycle.details.kgDryT': 'kg/t suchej masy',
      'cycle.details.chamber-name': 'Hala',
      'cycle.details.start-date': 'Data rozpoczęcia',
      'cycle.details.end-date': 'Data zakończenia',
      'cycle.details.area': 'Powierzchnia',
      'cycle.details.weight': 'Waga podłoża',
      'cycle.details.humidity': 'Wilgotność podłoża',
      'cycle.details.technologist': 'Prowadzący',
      'cycle.details.ton': 't',
      'cycle.details.meter': 'm',
      'cycle.details.subsoil': 'Podłoże',
      'cycle.details.mycelium': 'Grzybnia',

      'cycle.byBrigades.header': 'Brygady w cyklach',
      'cycle.byBrigades.cycle': 'Cykl/Brygada',
      'cycle.byBrigades.inne': 'Inne',
      'cycle.byBrigades.kraj': 'Kraj',
      'cycle.byBrigades.export': 'Eksport',
      'cycle.byBrigades.total': 'Suma',
      'cycle.byBrigades.quality': 'Jakość',

      'cycles.by-technologists': 'Podsumowanie cykli',
      'cycle.technologist.report.day': 'Dzień',
      'cycle.technologist.report.inne': 'Inne',
      'cycle.technologist.report.kraj': 'Kraj',
      'cycle.technologist.report.export': 'Eksport',
      'cycle.technologist.report.total': 'Suma',
      'cycle.technologist.report.quality': 'Jakość',
      'cycle.technologist.report.kgM': 'kg/m',
      'cycle.technologist.report.kgT': 'kg/t',
      'cycle.technologist.report.title': 'Statystyki cykli zamkniętych w okresie ',
      'cycle.technologist.report.cyclesAmount': 'Ilość cykli',
      'sales.report.header': 'Ilość sprzedanych grzybów',
      'sales.report.customer.name': 'Odbiorca',
      'sales.report.total': 'Suma',
      'report.types-by-pickers.breadcrumb.header': 'Zbiory wg zbieraczek',
      'report.types-by-pickers.quality': 'Jakość',
      'report.types-by-pickers.total': 'Suma',
      'report.types-by-picker.breadcrumb.header': 'Zbiory ',
      'report.types-by-picker.quality': 'Jakość',
      'report.types-by-picker.total': 'Suma',
      'report.type-by-pickers.pcs.on': 'Szt.',
      'report.type-by-pickers.pcs.off': 'Kg.',
      'HEADER.HOTEL_MENU': 'Hotel',
      'hotel.settings': 'Ustawienia',
      'hotel.settings.breadcrumb.header': 'Ustawienia hoteli',
      'hotel.settings.create.hotel.title': 'Nowy hotel',
      'hotel.settings.create.hotel.add-hotel-button': 'Nowy hotel',
      'hotel.settings.create.hotel.name': 'Nazwa',
      'hotel.settings.create.hotel.rooms-amount': 'Ilość pokoi',
      'hotel.settings.create.hotel.beds-amount': 'Ilość łóżek w pokoju',
      'hotel.settings.create.hotel.message.invalid-name': 'Nazwa nie może być pusta',
      'hotel.settings.create.hotel.cancel': 'Anuluj',
      'hotel.settings.create.hotel.save': 'Zapisz',
      'hotel.settings.hotel.rooms-amount': 'Ilość pokoi',
      'hotel.settings.hotel.beds-amount': 'Ilość łóżek',
      'hotel.settings.create.hotel.message.hotel-created-success': 'Hotel pomyślnie dodany',
      'hotel.booking': 'Rezerwacje',
      'hotel.room.name': 'Pokój',
      'hotel.bed.name': 'Łóżko',
      'hotel.modal.reservation.header': 'Nowy pobyt',
      'hotel.modal.reservation.booking': 'Meldunek',
      'hotel.modal.reservation.reservation': 'Rezerwacja',
      'hotel.modal.reservation.message.success': 'Nowa rezerwacja pomyślnie zapisana',
      'hotel.modal.booking.message.success': 'Nowy pobyt pomyślnie zapisany',
      'hotel.booking.breadcrumb.header': 'Rezerwacje',
      'hotel.modal.reservation.cancel': 'Anuluj',
      'hotel.modal.reservation.submit': 'Zapisz',
      'hotel.modal.reservation.startDate': 'Początek pobytu',
      'hotel.modal.reservation.endDate': 'Koniec pobytu',
      'hotel.modal.reservation.person': 'Gość hotelu',
      'hotel.modal.reservation.description': 'Opis',
      'hotel.modal.reservation-edit.header': 'Edycja rezerwacji',
      'hotel.modal.reservation.delete': 'Usuń rezerwację',
      'hotel.modal.reservation-edit.save': 'Zapisz',
      'hotel.modal.booking.reservation-deleted-message': 'Rezerwacja pomyślnie usunięta',
      'hotel.day.utilization': ' Ilość zajętych miejsc: ',
      'eastMushrooms.warehouse.reception.button.create-palette': 'Nowa paleta',
      'eastMushrooms.warehouse.reception.change.palette.type.modal.header':'Zmień typ palety',
      'eastMushrooms.warehouse.reception.change.palette.type.modal.save':'Zmień',
      'eastMushrooms.warehouse.reception.change.palette.type.modal.cancel':'Anuluj',
      'eastMushrooms.warehouse.reception.depot-label': 'Chłodnia',
      'eastMushrooms.warehouse.reception.pcs': 'szt.',
      'eastMushroomsWarehouseReceptionNotAssignedHarvestPalettes': 'Nieprzypisane palety',
      'eastMushrooms.warehouse.reception.reject-harvest-palette': 'zwrot',
      'eastMushrooms.warehouse.reception.accept-warehouse-palette': 'Wyślij paletę do chłodni',
      'eastMushrooms.warehouse.reception.palette.nr': 'Paleta nr',
      'eastMushrooms.warehouse.reception.palette.total.amount':'Ilość skrzyneczek',
      'eastMushrooms.warehouse.reception.no-remote-type-defined': 'Brak przypisania skupie',
      'eastMushrooms.warehouse.remote.type.name': 'Rodzaj w skupie',
      'eastMushrooms.warehouse.local.type.name': 'Rodzaj',
      'eastMushrooms.warehouse.remote.amount': 'Ilość',
      'eastMushrooms.warehouse.palette.name': 'Paleta nr ',
      'eastMushrooms.warehouse.assigned.palettes':'Sprzedaż',
      'eastMushrooms.warehouse.assigned.palettes.amount':'Ilość palet',
      'eastMushrooms.warehouse.assigned.palettes.total.amount.pcs':'Łączna ilość sztuk do wysyłki',
      'assignedWarehousePalettes': 'Wysyłka',
      'notAssignedPalettes': 'Magazyn',
      'eastMushrooms.warehouse.release-button': 'Sprzedaż',
      'eastMushrooms.wz.header.nr': 'Nr',
      'eastMushrooms.wz.header.date': 'Data',
      'eastMushrooms.wz.header.company': 'Wystawiający',
      'eastMushrooms.wz.header.customer': 'Odbiorca',
      'eastMushrooms.wz.header.amount': 'Ilość',
      'eastMushrooms.wz.template.header.name': 'Wydanie zewnętrzne nr ',
      'eastMushrooms.wz.template.header.date': ' z dnia ',
      'eastMushrooms.wz.template.ggn': 'GGN: ',
      'eastMushrooms.wz.template.header.supplier': 'Dostawca:',
      'eastMushrooms.wz.template.header.customer': 'Odbiorca:',
      'eastMushrooms.wz.template.localTypeName': 'Rodzaj',
      'eastMushrooms.wz.template.remoteTypeName': 'Rodzaj na skupie',
      'eastMushrooms.wz.template.weight': 'Waga',
      'eastMushrooms.wz.template.type.amount': 'Ilość',
      'eastMushrooms.wz.template.type.totalWeight': 'Łączna waga',
      'eastMushrooms.wz.template.palettes.list': 'Specyfikacja palet',
      'eastMushrooms.wz.template.paletteNr': 'Numer palety',
      'eastMushrooms.wz.template.amount': 'Ilość',
      'eastMushrooms.wz.template.totalWeight': 'Waga',
      'eastMushrooms.wz.template.creator': 'Wystawiający',
      'eastMushrooms.wz.template.receiver': 'Odbierający',
      'eastMushrooms.wz.template.total': 'Suma',
      'eastMushrooms.wz.breadcrumb.list': 'Dokumenty wydania',
      'eastMushrooms.wz.breadcrumb.document': 'Dokument wydania nr',
      'eastMushrooms.wz.template.total.palettes':'Łaczna ilość palet',
      'eastMushrooms.shipment.header.nr': 'Nr',
      'eastMushrooms.shipment.header.date': 'Data',
      'eastMushrooms.shipment.header.customer': 'Odbiorca',
      'eastMushrooms.shipment.header.amount': 'Ilość',
      'palette-types.breadcrump.header':'Kolejność sortowania rodzajów palet na listach wyboru',
      'eastMushrooms.shipment.title':'Wysyłka nr ',
      'eastMushrooms.shipment.date':' z dnia ',
      'eastMushrooms.shipment.toCustomer':' do odbiorcy: ',
      'eastMushrooms.shipment.wznr':'Nr WZ',
      'eastMushrooms.shipment.company':'Producent',
      'eastMushrooms.shipment.totalWeight':'Łączna waga',
      'eastMushrooms.shipment.breadcrumb.list':'Wysyłki',
      'eastMushrooms.shipment.breadcrumb.document':'Wysyłka nr:',
      'eastMushroooms.shipment.paletteNo':'Paleta nr',
      'eastMushrooms.shipment.wz-list':'Wysłane dokumenty WZ',
      'eastMushrooms.shipment.palette-list':'Wysłane palety',
      'eastMushrooms.shipment.type.name':'Rodzaj',
      'eastMushrooms.shipment.type.amount':'Łączna ilość',
      'eastMushrooms.shipment.type.weight':"Łączna waga",
      'eastMushrooms.shipment.paletteType.name':'Paleta',
      'eastMushrooms.shipment.paletteType.amount':'Ilość',
      'eastMushrooms.shipment.total':'Suma',
      'eastMushrooms.releases.breadcrumb': 'Wysyłki',
      'eastMushrooms.warehouse.stock.breadcrumb': 'Stan chłodni',
      'eastMushrooms.warehouse.stock.typeName': 'Rodzaj',
      'eastMushrooms.warehouse.stock.amount': 'Ilość sztuk',
      'eastMushrooms.warehouse.stock.weight': 'Łączna waga',
      'eastMushrooms.warehouse.stock.total': 'Suma',
      'eastMushrooms.warehouse.stock.palettes.amount': 'Ilość palet',
      'eastMushrooms.reclassification.reclassify-button': 'Przeklasyfikowanie',
      'eastMushrooms.reclassification.invalid.supplier.id.message': 'Niewłaściwy numer producenta',
      'eastMushrooms.reclassification.box.not.found.message': 'Brak skrzyneczki o podanym kodzie',
      'eastMushrooms.reclassification.box.released.message': 'Skrzyneczka figuruje jako już wysłana',
      'eastMushrooms.reclassification.box.created.message': 'Skrzyneczka jeszcze nie zatwierdzona do chłodni',
      'eastMushrooms.reclassification.box.already-scanned.message': 'Skrzyneczka już zeskanowana',
      'eastMushrooms.reclassification.box.success.message': 'Przyklasyfikowanie pomyślnie zakończone',

      'eastMushrooms.change.palette.paletteId': 'Numer palety',
      'eastMushrooms.change.palette.totalAmount': 'Łączna ilość sztuk',
      'eastMushroom.change.palette.move-button': 'Przenieś',
      'eastMushrooms.change.palette-whole': 'Łączenie palet',
      'eastMushrooms.change.palette-by-code': 'Przenoszenie skrzyneczek',
      'eastMushrooms.change.palette.by.box.button': 'Przenieś',
      'eastMushrooms.change.palette.by.box.new.palette.button': 'Nowa paleta',
      'eastMushrooms.change.palette.by.box.select.depot.header': 'Wybór chłodni do stworzenia nowej palety',
      'eastMushrooms.change.palette.by.box.new.palette.created.message': 'Nowa paleta pomyślnie utworzona',
      'eastMushrooms.change.palette.by.box.success.message': 'Skrzyneczki pomyślnie przeniesione',
      'eastMushrooms.change.palette.select.palette.header':'Wybór palety na którą zostaną przesunięte skrzyneczki z palety',
      'eastMushrooms.change.palette.select.palette.join.success.message':'Paleta pomyślnie przeniesiona',
      'orders.breadcrumb.header':'Zamówienia produkcyjne',
      'orders.warehouse.type':'Typ na skupie',
      'orders.local.type':'Typ w pieczarkarni',
      'orders.no.local.type':'Brak zdefiniowanego typu grzybów',

      'production.order.local.breadcrumb':'Zamówienia produkcyjne',
      'production.order.local.modal.close':'Anuluj',
      'production.order.local.modal.save':'Zapisz',
      'production.order.local.message.success':'Zamówienie zapisane',
      'report.trolleyManReport.header':'Raport pracy wagowych',
      'report.trolleyManReport.scaleMan':'Wagowy',
      'report.trolleyManReport.total':'Suma',
    });


    $translateProvider.preferredLanguage('pl');
//    $translateProvider.preferredLanguage('ru');
    $translateProvider.useSanitizeValueStrategy('escape');
  }]);
